services:
  mssqlserver:
    image: jlsilva01/satc-sql-server
    container_name: sql-server
    hostname: sql-server
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "satc@123"
    ports:
      - "1433:1433"
